<p align="justify">
<p>Um experimento  biol&oacute;gico utiliza  uma fita de papel branco  especial, na qual algumas  gotas de um reagente s&atilde;o colocadas em posi&ccedil;&otilde;es espec&iacute;ficas. Inicialmente  a gota de reagente faz com que o papel se torne  preto  na posi&ccedil;&atilde;o em que foi colocada.  A cada  dia o reagente  se propaga  pelo papel,  em todas  as dire&ccedil;&otilde;es,  com velocidade  de 1 posi&ccedil;&atilde;o por dia,  colorindo a regi&atilde;o em que o reagente se propagou.  A figura abaixo mostra  um experimento  com uma fita de 13 posi&ccedil;&otilde;es, com tr&ecirc;s gotas de reagente  inicialmente,  colocadas nas posi&ccedil;&otilde;es 2, 6 e 13 (a posi&ccedil;&atilde;o 1 &eacute; a primeira  mais &agrave; esquerda  da fita).  Ao final do terceiro  dia, a fita est&aacute; completamente tomada  pelo reagente.</p>

<p style="text-align: center;"><img title="Semente1" src="http://i.imgur.com/Uf1umvv.png" alt="Semente1" width="382" height="131" /></p>

<p>Voc&ecirc; foi contratado para  escrever um programa  que,  dados  o comprimento  da fita de papel  e as posi&ccedil;&otilde;es das gotas de reagente  no in&iacute;cio do experimento,  determine  quantos  dias ser&atilde;o necess&aacute;rios para  a fita de papel ficar completamente tomada  pelo reagente. <br /> <br /><strong>Entrada </strong><br />A primeira  linha cont&eacute;m  dois inteiros F  e R, indicando  respectivamente o comprimento da fita de papel,  em n&uacute;meros  de posi&ccedil;&otilde;es, e o n&uacute;mero  de gotas  no in&iacute;cio do experimento.  A segunda  linha cont&eacute;m R inteiros,  indicando  as posi&ccedil;&otilde;es das gotas de reagente,  que s&atilde;o dadas  em ordem crescente. <br /> <br /><strong>Sa&iacute;da </strong><br />Seu programa  deve produzir  uma &uacute;nica linha,  contendo  um &uacute;nico inteiro,  o n&uacute;mero  de dias necess&aacute;rios para  que a fita de papel fique totalmente tomada  pelo reagente. <br /> <br /><strong>Restri&ccedil;&otilde;es </strong><br />&bull; 1 &le; F &le; 100000, 1 &le; R &le; 1000 <br /> <br /><strong>Exemplo</strong></p>

<p><strong>Entrada </strong><br />13 3 <br />2 6 13 <br /> <br /><strong>Sa&iacute;da </strong><br />3 <br /> <br /><strong>Entrada </strong><br />10 2 <br />9 10 <br /> <br /><strong>Sa&iacute;da </strong><br />8</p>

